name: Update README Date

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite UTC
  workflow_dispatch: # Permite rodar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Atualizar a data no README
        run: |
          TODAY=$(date "+%d/%m/%Y")
          sed -i "s/<!--DATE-->/🗓️ **Data de hoje:** $TODAY/g" README.md

      - name: Commit e push das mudanças
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualizando data no README - $TODAY" || exit 0
          git push
